# Create a program that will play the “cows and bulls” game with the user. The game works like this:

# Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. For every digit that the user guessed correctly in the correct place, they have a “cow”. 
# For every digit the user guessed correctly in the wrong place is a “bull.” Every time the user makes a guess, tell them how many “cows” and “bulls” they have. Once the user guesses the correct number, the game is over. 
# Keep track of the number of guesses the user makes throughout teh game and tell the user at the end.

# Say the number generated by the computer is 1038. An example interaction could look like this:

#   Welcome to the Cows and Bulls Game! 
#   Enter a number: 
#   >>> 1234
#   2 cows, 0 bulls
#   >>> 1256
#   1 cow, 1 bull
#   ...





import random

def compare(user_input, num):
    cows = 0
    bulls = 0
    for i in range(len(num)):
        if user_input[i] == num[i]:
            cows += 1
        elif user_input[i] in num:
            bulls += 1
    return cows, bulls

if __name__=="__main__":
    start = True
    num = random.randint(1000, 9999)
    guesses = 0

    while start:
        user_input = input('enter a num: ')
        if user_input == str(num):
            guesses += 1
            print(f'you won, number of guesses: {guesses}')
            break
        else:
            guesses += 1
            print(f'cows: {compare(user_input, str(num))[0]}, bulls: {compare(user_input, str(num))[1]}')
